//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriangleChecker.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidatorRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidatorRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TriangleChecker.Resources.ValidatorRes", typeof(ValidatorRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse the input, please use integer values between [1:4294967295].
        /// </summary>
        public static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle is Equilateral.
        /// </summary>
        public static string ResultEquilateral {
            get {
                return ResourceManager.GetString("ResultEquilateral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle is Isosceles.
        /// </summary>
        public static string ResultIsosceles {
            get {
                return ResourceManager.GetString("ResultIsosceles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resultText.
        /// </summary>
        public static string ResultLabelid {
            get {
                return ResourceManager.GetString("ResultLabelid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Values.
        /// </summary>
        public static string ResultLabelText {
            get {
                return ResourceManager.GetString("ResultLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle with provided sides does NOT exist.
        /// </summary>
        public static string ResultNone {
            get {
                return ResourceManager.GetString("ResultNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle is Scalene.
        /// </summary>
        public static string ResultScalene {
            get {
                return ResourceManager.GetString("ResultScalene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string RunBtnText {
            get {
                return ResourceManager.GetString("RunBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sideA.
        /// </summary>
        public static string SideAid {
            get {
                return ResourceManager.GetString("SideAid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side A.
        /// </summary>
        public static string SideAPlaceholder {
            get {
                return ResourceManager.GetString("SideAPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sideB.
        /// </summary>
        public static string SideBid {
            get {
                return ResourceManager.GetString("SideBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side B.
        /// </summary>
        public static string SideBPlaceholder {
            get {
                return ResourceManager.GetString("SideBPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sideC.
        /// </summary>
        public static string SideCid {
            get {
                return ResourceManager.GetString("SideCid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side C.
        /// </summary>
        public static string SideCPlaceholder {
            get {
                return ResourceManager.GetString("SideCPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle with given sides exists, but it&apos;s type is unknown.
        /// </summary>
        public static string UnknownTriangleType {
            get {
                return ResourceManager.GetString("UnknownTriangleType", resourceCulture);
            }
        }
    }
}
